
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app-deployment
  labels:
    app: simple-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: simple-node-app
        image: your-dockerhub-username/simple-node-app:latest # IMPORTANT: Replace with your Docker Hub username and image tag
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-service
spec:
  type: NodePort
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080 # You can access the application on <EC2_IP>:30080
